# Generated by Django 3.0.7 on 2020-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='recordStatus',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Unverified', 'Unverified')], default='Unverified', max_length=10),
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
