# Generated by Django 3.0.7 on 2020-07-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200701_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='genoType',
        ),
    ]
