# Generated by Django 3.0.7 on 2020-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200716_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='medicalHistory',
        ),
        migrations.AddField(
            model_name='allergy',
            name='medicalHistory',
            field=models.ManyToManyField(related_name='allergy', to='record.MedicalHistory'),
        ),
        migrations.RemoveField(
            model_name='disease',
            name='medicalHistory',
        ),
        migrations.AddField(
            model_name='disease',
            name='medicalHistory',
            field=models.ManyToManyField(related_name='disease', to='record.MedicalHistory'),
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medicalHistory',
        ),
        migrations.AddField(
            model_name='medication',
            name='medicalHistory',
            field=models.ManyToManyField(related_name='medication', to='record.MedicalHistory'),
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='medicalHistory',
        ),
        migrations.AddField(
            model_name='surgery',
            name='medicalHistory',
            field=models.ManyToManyField(related_name='surgery', to='record.MedicalHistory'),
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='medicalHistory',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='medicalHistory',
            field=models.ManyToManyField(related_name='vaccination', to='record.MedicalHistory'),
        ),
    ]
