# Generated by Django 3.0.7 on 2020-07-02 01:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_medicalhistory_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='diseases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='surgeries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='vaccinations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
