# Generated by Django 3.0.7 on 2020-07-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20200716_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='medicalHistory',
            field=models.ManyToManyField(to='record.MedicalHistory'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='medicalHistory',
            field=models.ManyToManyField(to='record.MedicalHistory'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicalHistory',
            field=models.ManyToManyField(to='record.MedicalHistory'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='medicalHistory',
            field=models.ManyToManyField(to='record.MedicalHistory'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='medicalHistory',
            field=models.ManyToManyField(to='record.MedicalHistory'),
        ),
    ]
