# Generated by Django 3.0.7 on 2020-07-16 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20200702_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='surgeries',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='vaccinations',
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medicalHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to='record.MedicalHistory')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medicalHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='record.MedicalHistory')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medicalHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='record.MedicalHistory')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medicalHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='record.MedicalHistory')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medicalHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy', to='record.MedicalHistory')),
            ],
        ),
    ]
